# Generated by Django 2.2.3 on 2019-07-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('todo', 'To-Do'), ('inpr', 'In-Progress'), ('done', 'Done')], default='todo', max_length=4)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
